### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by davelab6** [impallari/Amika-Devanagari#3]
@etunni published https://github.com/etunni/Amita last year; I wonder if this name is too similar... Are you in love with this name? :)

**Comment by impallari** [comment]
I like Amika, it means "friendly" in esperanto... but will think about a new one.

**Comment by davelab6** [comment]
Ping :)

**Comment by impallari** [comment]
I'm thinking about it. Any suggestion?

**Comment by davelab6** [comment]
Maybe some area or landmark of Mumbai from your visit? browsing the map
pulls up things

Hariom

Dadar

Fitwalla

**Comment by impallari** [comment]
Renamed to Amiko
